#!/usr/bin/env bash
# logos-publish.sh — publish an app's BUILT artifacts to a self-hosted Logos
# Basecamp package repo and/or a self-hosted F-Droid repo, regenerating the
# signed indexes so the desktop/phone see the new version.
#
# App-agnostic: you point it at the .lgx(s) and/or .apk you already built (see
# the logos-basecamp-module / logos-mobile-app skills for how to build them).
# It does NOT build; it publishes. Idempotent — re-running republishes.
#
# USAGE
#   logos-publish.sh \
#       [--lgx FILE]...                       # one or more Basecamp module .lgx (portable/linux-amd64)
#       [--apk FILE --apk-package ID          # the release APK + its applicationId
#          [--apk-name "Name"] [--apk-summary "One line"] [--apk-category Cat]
#          [--apk-source URL]]
#       [--no-fdroid-update]                  # copy the APK but skip `fdroid update` (batch several first)
#
# ENV (defaults suit this host; override for a different setup)
#   BASECAMP_REPO   ${BASECAMP_REPO:-$HOME/vpavlin-home/basecamp}   # dir the LAN Basecamp server serves
#   REPO_NAME       ${REPO_NAME:-vpavlin-home}                      # catalog id (logos-repo.json)
#   REPO_DISPLAY    ${REPO_DISPLAY:-vpavlin @ home}
#   REPO_HOST       ${REPO_HOST:-<first hostname -I addr>}
#   REPO_PORT       ${REPO_PORT:-8444}
#   FDROID_HOME     ${FDROID_HOME:-$HOME/fdroid}                    # has repo/ metadata/ config.yml keystore
#   FDROID_BIN      ${FDROID_BIN:-$HOME/fdroid-venv/bin/fdroid}
#   ANDROID_HOME, JAVA_HOME                                         # for fdroid/aapt2 (defaults probed)
#
# WHY IT'S SHAPED THIS WAY (the traps this script encodes so you don't re-hit them):
#  - Publish the PORTABLE (linux-amd64) .lgx, never a `-dev` build — a -dev .lgx
#    shows "NOT AVAILABLE" in Basecamp's package manager.
#  - The Basecamp index is regenerated by scanning EVERY *.lgx in the repo dir,
#    so multiple apps coexist; dropping a new/updated .lgx and rescanning is all
#    it takes. logos-repo.json (the catalog identity card, https indexUrl) is
#    created once and left alone.
#  - F-Droid REQUIRES a metadata/<pkg>.yml or `fdroid update` yields an EMPTY
#    index (the device sees no app). This script auto-creates a minimal one.
#  - Publish to the repo the client ACTUALLY reads. Verify from there, not dist/.
set -euo pipefail

BASECAMP_REPO="${BASECAMP_REPO:-$HOME/vpavlin-home/basecamp}"
REPO_NAME="${REPO_NAME:-vpavlin-home}"
REPO_DISPLAY="${REPO_DISPLAY:-vpavlin @ home}"
REPO_HOST="${REPO_HOST:-$(hostname -I | awk '{print $1}')}"
REPO_PORT="${REPO_PORT:-8444}"
FDROID_HOME="${FDROID_HOME:-$HOME/fdroid}"
FDROID_BIN="${FDROID_BIN:-$HOME/fdroid-venv/bin/fdroid}"
export ANDROID_HOME="${ANDROID_HOME:-$HOME/Android/Sdk}"
export JAVA_HOME="${JAVA_HOME:-/usr/lib/jvm/java-17-openjdk-amd64}"

LGXS=(); APK=""; APK_PKG=""; APK_NAME=""; APK_SUMMARY=""; APK_CATEGORY="Internet"; APK_SOURCE=""; DO_FDROID_UPDATE=1
while [ $# -gt 0 ]; do
  case "$1" in
    --lgx) LGXS+=("$2"); shift 2;;
    --apk) APK="$2"; shift 2;;
    --apk-package) APK_PKG="$2"; shift 2;;
    --apk-name) APK_NAME="$2"; shift 2;;
    --apk-summary) APK_SUMMARY="$2"; shift 2;;
    --apk-category) APK_CATEGORY="$2"; shift 2;;
    --apk-source) APK_SOURCE="$2"; shift 2;;
    --no-fdroid-update) DO_FDROID_UPDATE=0; shift;;
    *) echo "unknown arg: $1" >&2; exit 2;;
  esac
done
[ "${#LGXS[@]}" -eq 0 ] && [ -z "$APK" ] && { echo "nothing to publish: pass --lgx and/or --apk" >&2; exit 2; }
BASE="https://${REPO_HOST}:${REPO_PORT}"

# ---------- Basecamp: install .lgx(s) + regenerate the catalog index ----------
if [ "${#LGXS[@]}" -gt 0 ]; then
  mkdir -p "$BASECAMP_REPO"
  for lgx in "${LGXS[@]}"; do
    [ -f "$lgx" ] || { echo "no such .lgx: $lgx" >&2; exit 1; }
    # sanity + read the module name: a portable module manifest has name + hashes.root
    mname=$(tar xzOf "$lgx" manifest.json 2>/dev/null | python3 -c "import sys,json;print(json.load(sys.stdin)['name'])" 2>/dev/null) \
      || { echo "not a valid .lgx (no manifest.json): $lgx" >&2; exit 1; }
    # STABLE per-module filename (overwrite the previous version) — a single-latest
    # repo lists ONE .lgx per module; a versioned filename would accumulate and the
    # index (which lists every *.lgx) would show duplicate entries for the module.
    dest="logos-${mname}-module.lgx"
    install -m644 "$lgx" "$BASECAMP_REPO/$dest"
    echo "  + basecamp: $dest  (${mname} $(tar xzOf "$lgx" manifest.json 2>/dev/null | python3 -c "import sys,json;print(json.load(sys.stdin).get('version','?'))" 2>/dev/null))" >&2
  done
  # catalog identity card — create once, never clobber a multi-app catalog
  if [ ! -f "$BASECAMP_REPO/logos-repo.json" ]; then
    cat > "$BASECAMP_REPO/logos-repo.json" <<JSON
{
  "schemaVersion": 1,
  "name": "${REPO_NAME}",
  "displayName": "${REPO_DISPLAY}",
  "description": "Logos Basecamp modules served on the local network.",
  "homepage": "https://github.com/${USER}",
  "indexUrl": "${BASE}/basecamp/index.json",
  "trustedSigners": []
}
JSON
  fi
  # regenerate index.json by scanning EVERY .lgx (all apps stay listed)
  ( cd "$BASECAMP_REPO" && python3 - "${BASE}/basecamp" "$REPO_NAME" <<'PY' > index.json
import glob, hashlib, json, subprocess, sys, datetime
base, repo = sys.argv[1], sys.argv[2]; packages = []
now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
for lgx in sorted(glob.glob("*.lgx")):
    try: m = json.loads(subprocess.check_output(["tar","xzOf",lgx,"manifest.json"]))
    except Exception as e: print(f"skip {lgx}: {e}", file=sys.stderr); continue
    data = open(lgx,"rb").read()
    packages.append({"name": m["name"], "versions": [{
        "releasedAt": now, "publisherRef": f"{m['name']}-v{m.get('version','0.0.0')}",
        "url": f"{base}/{lgx}", "size": len(data), "sha256": hashlib.sha256(data).hexdigest(),
        "rootHash": m["hashes"]["root"], "manifest": m}]})
json.dump({"schemaVersion":2,"repositoryName":repo,"generatedAt":now,"packages":packages}, sys.stdout, indent=2); print()
PY
  )
  echo "  basecamp index -> $BASE/basecamp/logos-repo.json  ($(ls "$BASECAMP_REPO"/*.lgx | wc -l) package(s))" >&2
fi

# ---------- F-Droid: ensure metadata, copy APK, regenerate signed index ----------
if [ -n "$APK" ]; then
  [ -f "$APK" ] || { echo "no such apk: $APK" >&2; exit 1; }
  [ -n "$APK_PKG" ] || { echo "--apk requires --apk-package <applicationId>" >&2; exit 2; }
  [ -d "$FDROID_HOME/repo" ] || { echo "F-Droid repo not initialized at $FDROID_HOME (run: fdroid init)" >&2; exit 1; }
  BT=$(ls -d "$ANDROID_HOME"/build-tools/*/ 2>/dev/null | sort -V | tail -1)
  export PATH="$JAVA_HOME/bin:${BT}:$ANDROID_HOME/platform-tools:$PATH"
  mkdir -p "$FDROID_HOME/metadata"
  META="$FDROID_HOME/metadata/${APK_PKG}.yml"
  if [ ! -f "$META" ]; then                       # REQUIRED or the index comes out empty
    cat > "$META" <<YML
AuthorName: ${USER}
Categories:
  - ${APK_CATEGORY}
Name: ${APK_NAME:-$APK_PKG}
Summary: ${APK_SUMMARY:-Logos app}
Description: |-
  ${APK_SUMMARY:-A Logos app.}
${APK_SOURCE:+SourceCode: $APK_SOURCE}
CurrentVersionCode: 2147483647
YML
    echo "  + fdroid metadata: metadata/${APK_PKG}.yml (created)" >&2
  fi
  cp -f "$APK" "$FDROID_HOME/repo/$(basename "$APK")"
  echo "  + fdroid: repo/$(basename "$APK")" >&2
  if [ "$DO_FDROID_UPDATE" -eq 1 ]; then
    ( cd "$FDROID_HOME" && "$FDROID_BIN" update --pretty < /dev/null >/dev/null 2>&1 ) \
      && echo "  fdroid index regenerated -> $BASE/fdroid/repo" >&2 \
      || { echo "  fdroid update FAILED — run manually: (cd $FDROID_HOME && $FDROID_BIN update --pretty)" >&2; exit 1; }
  fi
fi

# ---------- verify from the published path ----------
echo "== published ==" >&2
if [ "${#LGXS[@]}" -gt 0 ] && [ -f "$BASECAMP_REPO/index.json" ]; then
  python3 -c "import json;d=json.load(open('$BASECAMP_REPO/index.json'));print('  basecamp:', [(p['name'], p['versions'][-1]['manifest'].get('version')) for p in d['packages']])"
fi
if [ -n "$APK" ] && [ -f "$FDROID_HOME/repo/index-v1.json" ]; then
  python3 -c "import json;d=json.load(open('$FDROID_HOME/repo/index-v1.json'));print('  fdroid:', {p:[(v.get('versionName'),v.get('versionCode')) for v in vs] for p,vs in d['packages'].items()})" 2>/dev/null || true
fi
echo "  NOTE: confirm on a CLEAN client (Basecamp package manager refresh / F-Droid pull), not from dist/." >&2
